language: python

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    python: '3.4'
  - os: linux
    dist: trusty
    sudo: required
    python: '3.5'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.6'
  - os: linux
    dist: trusty
    sudo: required
    python: '3.6-dev'
  
before_install:
  - set -e
  - if [[ "$TRAVIS_PYTHON_VERSION" != "3.4" && "$TRAVIS_PYTHON_VERSION" != "3.5" ]]; then
      pip install pyqt5;
    else
      source $TRAVIS_BUILD_DIR/.travis/build_pyqt5.sh;
    fi
# command to install dependencies
install:
  - python setup.py install
# command to run tests
script:
  - pytest

# safelist
branches:
  only:
  - master
  - dev
  - travis