language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
install:
  - python setup.py install
# command to run tests
script:
  - pytest

# safelist
branches:
  only:
  - master
  - dev
  - travis